// ISO 3166-1 alpha-2 codes → flagcdn.com images work on all platforms
const ISO: Record<string, string> = {
  // CONCACAF
  'United States': 'us', 'USA': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Panama': 'pa',
  'Costa Rica': 'cr',
  'Honduras': 'hn',
  'Jamaica': 'jm',
  'Guatemala': 'gt',
  'Cuba': 'cu',
  'El Salvador': 'sv',
  'Trinidad and Tobago': 'tt',

  // CONMEBOL
  'Brazil': 'br',
  'Argentina': 'ar',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Paraguay': 'py',
  'Bolivia': 'bo',
  'Venezuela': 've',
  'Chile': 'cl',
  'Peru': 'pe',

  // UEFA
  'France': 'fr',
  'Germany': 'de',
  'Spain': 'es',
  'England': 'gb-eng',
  'Netherlands': 'nl',
  'Portugal': 'pt',
  'Italy': 'it',
  'Belgium': 'be',
  'Serbia': 'rs',
  'Switzerland': 'ch',
  'Poland': 'pl',
  'Croatia': 'hr',
  'Czech Republic': 'cz', 'Czechia': 'cz',
  'Denmark': 'dk',
  'Slovakia': 'sk',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Austria': 'at',
  'Turkey': 'tr', 'Türkiye': 'tr',
  'Romania': 'ro',
  'Hungary': 'hu',
  'Ukraine': 'ua',
  'Bosnia-Herzegovina': 'ba', 'Bosnia and Herzegovina': 'ba', 'Bosnia & Herzegovina': 'ba',
  'Kosovo': 'xk',
  'Slovenia': 'si',
  'Albania': 'al',
  'Greece': 'gr',
  'Norway': 'no',
  'Sweden': 'se',
  'Finland': 'fi',
  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Iceland': 'is',
  'Georgia': 'ge',
  'Bulgaria': 'bg',
  'Ireland': 'ie',
  'Northern Ireland': 'gb-nir',
  'Luxembourg': 'lu',
  'Moldova': 'md',
  'Armenia': 'am',
  'Azerbaijan': 'az',
  'Belarus': 'by',
  'Cyprus': 'cy',
  'Estonia': 'ee',
  'Latvia': 'lv',
  'Lithuania': 'lt',

  // CAF
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Egypt': 'eg',
  'Nigeria': 'ng',
  'South Africa': 'za',
  'Cameroon': 'cm',
  'Ghana': 'gh',
  'DR Congo': 'cd', 'Congo DR': 'cd', 'Democratic Republic of Congo': 'cd',
  'Algeria': 'dz',
  "Ivory Coast": 'ci', "Côte d'Ivoire": 'ci', "Cote d'Ivoire": 'ci',
  'Mali': 'ml',
  'Cape Verde': 'cv',
  'Tunisia': 'tn',
  'Angola': 'ao',
  'Gabon': 'ga',
  'Zambia': 'zm',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Benin': 'bj',
  'Comoros': 'km',
  'Guinea': 'gn',
  'Burkina Faso': 'bf',
  'Mozambique': 'mz',
  'Libya': 'ly',
  'Equatorial Guinea': 'gq',
  'Sudan': 'sd',
  'Rwanda': 'rw',
  'Mauritania': 'mr',
  'Namibia': 'na',

  // AFC
  'Japan': 'jp',
  'South Korea': 'kr', 'Korea Republic': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Qatar': 'qa',
  'Jordan': 'jo',
  'Oman': 'om',
  'Uzbekistan': 'uz',
  'Iraq': 'iq',
  'UAE': 'ae', 'United Arab Emirates': 'ae',
  'Bahrain': 'bh',
  'China': 'cn', 'China PR': 'cn',
  'India': 'in',
  'Indonesia': 'id',
  'Palestine': 'ps',
  'Thailand': 'th',
  'Vietnam': 'vn',
  'Kuwait': 'kw',
  'Kyrgyzstan': 'kg',
  'Syria': 'sy',
  'Tajikistan': 'tj',
  'Yemen': 'ye',

  // OFC
  'New Zealand': 'nz',
  'Papua New Guinea': 'pg',
  'Fiji': 'fj',
  'Tahiti': 'pf',
  'Solomon Islands': 'sb',
  'Vanuatu': 'vu',
  'New Caledonia': 'nc',
}

export function getFlagUrl(team: string, size: '20x15' | '40x30' = '20x15'): string | null {
  const code = ISO[team]
  if (!code) return null
  return `https://flagcdn.com/${size}/${code}.png`
}
